### ISSUE TITLE
Proactive Remediation for Business: "AtLogin" does not work

### ISSUE THREAD

**Issue by Psychotec50** [FlorianSLZ/scloud#10]
Great tools and scripts, I really appreciate the work you put into it.

I found an issue when using the "AtLogin" configuration in the "Proactive Remediation for Business"-scripts:
When I deploy the script as "user" in Intunes, it failes to create the scheduled task for all users which do not have local admin rights. ("Register-Scheduler: access denied") - both on Win 10 and 11.

When I deploy it as "system" in Intune, it creates a task for "SYSTEM" with the packagename and machine name, but not for the respective logged-in user.

Happy to provide more logs or help debugging

**Comment by FlorianSLZ** [comment]
Thanks for your feedback. 
I've tested the behavior and updatet the script to prevent the "access denied" error.
